language: ruby
cache: bundler
sudo: false
rvm:
- 2.1
- 2.2
branches:
  only:
  - master
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: DDrKE+td2eGF7eAPuESBcOoRAnzY/faXrX+HvM+Zpgke9ZE8y+ICYfkzr/DllQBIvIRrtwJgq5cPeBRH4hjgyACjv5HhJDR84KNL+apR6IGi+Z0LevS2DWaNaFWc5AEus5PdybRSHwHshQGl8k9s/HAnUAzuazPwZZNdCviuLMPViokX2r3+ecNM85psXHPC64Wxm3PhZzXXW+TsPgWG5mIgx2XriHxgnd7V/cBKA+6ldye27CaB2o9MS5uEFlfZj2PhqCRcBxvi82siziOnDyLjPxkjvNVPPf/QB4Lr+Zzi6rl7Gg1/qFoM83XuckfYbLUczYKYMOKjhkhBFvkzeJRUpRjK0TEZx3fRZ4we4PonprE66zZ1vAnOv/yHW26nKtUiMAZ+TCU8SAEgmAfHEiVazjvE9Ev+wbbsQtVskoVbnw1EJJwyKbVzMNCyZ4fVD6r6vBNFo2IWjL+6DJ21wMjR32a92DWYprGpkbwAaNzYe1zjPZsfAy/6JhW6Hd5qFgyEsq4ZjVDu3ELl2iN3B6DlCZEFyM/yrYCv9jlBZk6htkE3v3uXZOmld1Uxs636IQfYyRnY4BqnyYAxM7z88+N1LrOTXKj7RLLFF0WEWA9kOKvPiuQ3K+BOb0tv0hwulZJGXkeT1QKZtyItj5qSMeZvnVx+b1Y/b+5G5v09C+g=
